# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Bash@3
  displayName: 'Delete plexus-classworlds.license'
  inputs:
    targetType: 'inline'
    script: |
      cd $M2_HOME/boot
      ls -la
      rm ./plexus-classworlds.license
- task: ArtifactoryMaven@1
  inputs:
    mavenPomFile: 'maven-example/pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'rtf'
    targetResolveReleaseRepo: 'maven-releases-virtual'
    targetResolveSnapshotRepo: 'maven-snapshots-virtual'
    artifactoryDeployService: 'rtf'
    targetDeployReleaseRepo: 'lzw-maven-dev-local'
    targetDeploySnapshotRepo: 'lzw-maven-dev-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'rtf'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'rtf'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'lzw-maven-pro-local'
    status: 'Released'
    sourceRepo: 'lzw-maven-dev-local'
    includeDependencies: true
    copy: true
    dryRun: false
- task: ArtifactoryPromoterPlus@0
  inputs:
    artifactoryService: 'rtf-platform'
    sourceRepo: 'generic-local'
    sourcePath: '/test/controlconfig.conf'
    targetRepo: 'demo-generic-local'
    targetPath: '/test/controlconfig.conf'
    status: 'Deployed'
    copy: 'true'
    artifacts: true
    dryRun: false
    failFast: true
- task: ArtifactoryProperties@1
  inputs:
    command: 'set'
    artifactoryService: 'rtf'
    setProps: 'test.platforms=ubuntu-16.04,x86_64;'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "build": "$(Build.DefinitionName)/$(Build.BuildNumber)"
          }
        ]
      }
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'rtf'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
