# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Bash@3
  displayName: 'Delete plexus-classworlds.license'
  inputs:
    targetType: 'inline'
    script: |
      cd $M2_HOME/boot
      ls -la
      rm ./plexus-classworlds.license
- task: ArtifactoryMaven@1
  inputs:
    mavenPomFile: 'maven-example/pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'rtf-demo'
    targetResolveReleaseRepo: 'maven-releases-virtual'
    targetResolveSnapshotRepo: 'maven-snapshots-virtual'
    artifactoryDeployService: 'rtf-demo'
    targetDeployReleaseRepo: 'lzw-maven-dev-local'
    targetDeploySnapshotRepo: 'lzw-maven-dev-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'rtf-demo'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'lzw-maven-pro-local'
    status: 'Released'
    sourceRepo: 'lzw-maven-dev-local'
    includeDependencies: true
    copy: true
    dryRun: false
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'rtf-demo'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
